export default function List() {

    const list = [

        // Beverages, non-alcoholic (including soft drinks and juices)

        {name: "Apple juice, unsweetened", density: 1.04},
        {name: "Tonic water, carbonated", density: 1.04},
        {name: "Cranberry juice, bottled", density: 1.05},
        {name: "Fruit juice", density: 1.06},
        {name: "Grape juice", density: 1.054},
        {name: "Grape juice, unsweetened", density: 1.06},
        {name: "Guanabana nectar, canned", density: 1.02},
        {name: "Guava nectar, canned", density: 1.02},
        {name: "Lemonade, frozen concentrate, pink", density: 1.24},
        {name: "Lemonade, frozen concentrate, white", density: 1.17},
        {name: "Mango nectar, canned", density: 1},
        {name: "Orange juice", density: 1.038},
        {name: "Orange juice, unsweetened", density: 1.04},
        {name: "Orange soda, sweetened with sugar", density: 1.029},
        {name: "Soy drink", density: 1.08},
        {name: "Soya with sugar", density: 1.05},
        {name: "Soya with milk and sugar", density: 1.05},
        {name: "Tamarind nectar, canned", density: 1.01},

        // Water and ice

        {name: "Water (plain)", density: 1},
        {name: "Water, crushed ice", density: 0.65},
        {name: "Water, ice, 0 °C", density: 0.916},
        {name: "Water, ice, 4 °C", density: 0.999},
        {name: "Water, liquid, 20 °C", density: 0.998},
        {name: "Water, mineral water", density: 1.035},

        // Tea, cacao, coffee and drinking powders

        {name: "Chocolate drink powder", density: 0.5},
        {name: "Coffee, brewed", density: 1},
        {name: "Coffee, expresso", density: 1},
        {name: "Coffee, green (beans)", density: 0.60},
        {name: "Coffee, powder (nescafé)", density: 0.25},
        {name: "Coffee, roasted (beans)", density: 0.36},
        {name: "Miso broth", density: 1.06},
        {name: "Tea, black (tea leaves)", density: 0.48},
        {name: "Tea, herbal, Ciakimora leaves", density: 0.23},
        {name: "Tea, herbal, Ciakimora (leaves and water)", density: 1},
        {name: "Tea, flakes", density: 0.38},
        {name: "Tea, powdered", density: 0.43},
        {name: "Tea, liquid", density: 1},

        // Beverages, alcoholic

        {name: "Beer, light", density: 1},
        {name: "Beer, pilsner", density: 1.007},
        {name: "Alcohol, ethyl", density: 0.789},
        {name: "Liqueur", density: 1.1},
        {name: "Spirits, 45% alcohol", density: 0.939},
        {name: "Spirits, 70% alcohol", density: 0.885},
        {name: "Spirits, 75% alcohol", density: 0.873},
        {name: "Wine, red", density: 0.99},
        {name: "Wine, white", density: 0.99},

        // Milk products

        {name: "Milk (non-fat dry)", density: 0.56},
        {name: "Milk (powdered)", density: 0.21},
        {name: "Milk (powdered whole)", density: 0.56},
        {name: "Milk, acidophilus cultured", density: 1.01},
        {name: "Milk, buttermilk", density: 1.022},
        {name: "Milk, chocolate milk, skimmed", density: 1.056},
        {name: "Milk, coconut", density: 1.025},
        {name: "Milk, coconut (powdered)", density: 0.406},
        {name: "Milk, goat, whole", density: 1.08},
        {name: "Milk, liquid, skimmed", density: 1.033},
        {name: "Milk, liquid, partially skimmed", density: 1.034},
        {name: "Milk, liquid, whole", density: 1.030},

        // Dairy products

        {name: "Butter (regular)", density: 0.911},
        {name: "Butter, margarine", density: 0.96},
        {name: "Buttermilk, dried", density: 0.5},
        {name: "Casein", density: 0.58},
        {name: "Cheese, emmentaler, grated", density: 0.34},
        {name: "Cream cheese", density: 0.951},
        {name: "Cream, 9% fat", density: 1.017},
        {name: "Cream, 13% fat", density: 1.013},
        {name: "Cream, 38% fat", density: 0.984},
        {name: "Cream, heavy", density: 0.994},
        {name: "Cream, light", density: 1.012},
        {name: "Cream, sour 18% fat", density: 1.005},
        {name: "Cream, sour 38% fat", density: 0.978},
        {name: "Cream, whipped", density: 0.496},
        {name: "Ice cream", density: 0.554},
        {name: "Ice cream, rich", density: 0.62},
        {name: "Ice cream, no sugar added", density: 0.54},
        {name: "Ice cream, light (formerly ice milk)", density: 0.56},
        {name: "Ice cream, light, no sugar added", density: 0.58},
        {name: "Sour milk, cow, whole", density: 0.98},
        {name: "Yoghurt, plain, unsweetened", density: 1.06},

        // Oils

        {name: "Oil, nutmeg butter", density: 0.921},
        {name: "Oil, palmoil", density: 0.89},
        {name: "Oil, sunflower", density: 0.96},
        {name: "Oil, vegetable, coconut", density: 0.924},
        {name: "Oil, vegetable, corn", density: 0.922},
        {name: "Oil, vegetable, olive", density: 0.918},
        {name: "Oil, vegetable, palm", density: 0.915},
        {name: "Oil, vegetable, peanut", density: 0.914},
        {name: "Oil, vegetable, soya", density: 0.927},

        // Fats and other

        {name: "Animal fat", density: 0.7},
        {name: "Lard", density: 0.919},
        {name: "Mayonnaise, light", density: 1},
        {name: "Mayonnaise, traditional", density: 0.91},
        {name: "Peanut butter", density: 1.01},
        {name: "Solid vegetable fat kimbo", density: 0.6},
        {name: "Solid vegetable fat rina", density: 0.67},

        // Cereal and cereal products

        {name: "All Purpose Flour", density: 0.507},
        {name: "Almond Flour", density: 0.406},
        {name: "Barley", density: 0.62},
        {name: "Barley, flour", density: 0.61},
        {name: "Barley, ground", density: 0.40},
        {name: "Barley, malted", density: 0.49},
        {name: "Barley malt, flour", density: 0.72},
        {name: "Barley, flour, malted", density: 0.64},
        {name: "Barley, fine ground", density: 0.74},
        {name: "Barley, meal", density: 0.45},
        {name: "Barley, rolled", density: 0.36},
        {name: "Barley, scoured", density: 0.66},
        {name: "Barley, whole", density: 0.65},
        {name: "Breadcrumbs", density: 0.45},
        {name: "Breadcrumbs, panko", density: 0.237},
        {name: "Buckwheat, bran", density: 0.25},
        {name: "Buckwheat, flour", density: 0.66},
        {name: "Buckwheat, whole", density: 0.63},
        {name: "Donut mix", density: 0.64},
        {name: "Dough mix", density: 0.59},
        {name: "Millet", density: 0.64},
        {name: "Millet flour, bulrush", density: 0.56},
        {name: "Millet flour, finger", density: 0.61},
        {name: "Oat Flour", density: 0.53},
        {name: "Oat middlings", density: 0.61},
        {name: "Oats", density: 0.41},
        {name: "Oats groats, whole", density: 0.74},
        {name: "Oats, ground", density: 0.46},
        {name: "Oats, hulls", density: 0.13},
        {name: "Oats, rolled", density: 0.34},
        {name: "Quinoa, cooked", density: 0.782},
        {name: "Quinoa, raw", density: 0.719},
        {name: "Rice", density: 0.72},
        {name: "Rice, boiled", density: 0.73},
        {name: "Rice, boiled with fat", density: 0.70},
        {name: "Rice, bran", density: 0.42},
        {name: "Rice, brown, boiled", density: 0.85},
        {name: "Rice, brown, raw", density: 0.78},
        {name: "Rice, hulled", density: 0.75},
        {name: "Rice, puffed", density: 0.1},
        {name: "Rice, raw", density: 0.85},
        {name: "Rice, rough", density: 0.58},
        {name: "Rice, white, boiled", density: 0.73},
        {name: "Rice, white, raw", density: 0.82},
        {name: "Rye", density: 0.72},
        {name: "Rye, bran", density: 0.28},
        {name: "Rye, flour", density: 0.67},
        {name: "Rye, malted", density: 0.51},
        {name: "Rye, middlings", density: 0.67},
        {name: "Rye, shorts", density: 0.54},
        {name: "Rye, whole", density: 0.70},
        {name: "Semolina, raw", density: 0.78},
        {name: "Sorghum, flour", density: 0.54},
        {name: "Sorghum, fermented flour", density: 0.54},
        {name: "Sorghum, seed", density: 0.53},
        {name: "Soy, flour", density: 0.7},
        {name: "Soya, flour", density: 0.64},
        {name: "Wheat (regular)", density: 0.77},
        {name: "Wheat (regular), bran", density: 0.22},
        {name: "Wheat (regular), cracked", density: 0.56},
        {name: "Wheat (regular), cut", density: 0.74},
        {name: "Wheat (regular), flour", density: 0.58},
        {name: "Wheat (regular), flour, malted", density: 0.66},
        {name: "Wheat (regular), flour, white", density: 0.67},
        {name: "Wheat (regular), flour, wholemeal", density: 0.55},
        {name: "Wheat (regular), gluten", density: 0.69},
        {name: "Wheat (regular), hulls", density: 0.7},
        {name: "Wheat (regular), middlings", density: 0.24},
        {name: "Wheat (regular), shaved", density: 0.54},
        {name: "Wheat (regular), whole", density: 0.77},
        {name: "Whey", density: 0.56},
        
        // Tubers and products

        {name: "Cassava, flour", density: 0.55},
        {name: "Cassava, boiled", density: 0.63},
        {name: "Cassava, raw", density: 0.63},
        {name: "Potato, english, boiled", density: 0.59},
        {name: "Potato, english, raw", density: 0.59},
        {name: "Potato, flakes", density: 0.21},
        {name: "Potato, powdered", density: 0.77},
        {name: "Sweet potato, boiled", density: 0.65},
        {name: "Sweet potato, raw", density: 0.44},
        {name: "Yam, boiled", density: 0.79},
        {name: "Yam, raw", density: 0.66},

        // Nuts and seeds

        {name: "Almonds", density: 0.46},
        {name: "Almond Meal", density: 0.423},
        {name: "Cashews", density: 0.5},
        {name: "Coconut Chips", density: 0.61},
        {name: "Flaxseed", density: 0.7},
        {name: "Nuts", density: 0.63},
        {name: "Peanuts", density: 0.53},
        {name: "Peanuts, shelled", density: 0.69},
        {name: "Peanuts, unshelled", density: 0.33},
        {name: "Pistachio, with shell", density: 0.6},
        {name: "Pistachio, without shell", density: 0.646},
        {name: "Rapeseed", density: 0.77},
        {name: "Sunflower seed", density: 0.62},

        // Vegetables

        {name: "Alfalfa, leaf, meal", density: 0.23},
        {name: "Alfalfa, meal, dehydrated 13%", density: 0.275},
        {name: "Alfalfa, meal, dehydrated 17%", density: 0.32},
        {name: "Alfalfa, meal, fine ground", density: 0.30},
        {name: "Alfalfa, meal, suncured 13%", density: 0.22},
        {name: "Alfalfa, seed", density: 0.74},
        {name: "Alfalfa, stem meal", density: 0.19},
        {name: "Carrot, raw, chopped", density: 0.54},
        {name: "Carrot, raw, grated", density: 0.71},
        {name: "Cauliflower, boiled", density: 0.45},
        {name: "Chili, green", density: 0.5},
        {name: "Chili, red", density: 0.5},
        {name: "Chili, red, flakes", density: 0.487},
        {name: "Coriander (cilantro) leaves, raw", density: 0.068},
        {name: "Corn/maize, green, sweet corn, boiled", density: 0.73},
        {name: "Corn/maize, green, sweet corn, raw", density: 0.61},
        {name: "French green beans", density: 0.53},
        {name: "Fresh green peas (minji)", density: 0.73},
        {name: "Ginger root, raw", density: 0.406},
        {name: "Managu, leaves, raw", density: 0.2},
        {name: "Olives, green, with stone", density: 0.65},
        {name: "Onions, chopped", density: 0.22},
        {name: "Onions, leaves, spring onion, raw", density: 0.44},
        {name: "Onions, minced", density: 0.13},
        {name: "Onions, powdered", density: 0.4},
        {name: "Onions, fried, cubed", density: 0.75},
        {name: "Onions, raw, cubed", density: 0.55},
        {name: "Salad, green, leaves, raw", density: 0.06},
        {name: "Spinach, frozen, cooked", density: 1.046},
        {name: "Spinach, leaves, raw", density: 0.08},
        {name: "Sweet pepper, raw, cubes", density: 0.51},
        {name: "Sweet pepper, raw, half rings", density: 0.39},
        {name: "Tomato paste", density: 0.951},

        // Legumes

        {name: "Beans, white", density: 0.73},
        {name: "Cowpeas", density: 0.72},
        {name: "Cowpeas, dried, boiled", density: 0.75},
        {name: "Cowpeas, dried, raw", density: 0.96},
        {name: "Greengram, boiled", density: 0.76},
        {name: "Greengram, raw", density: 0.79},
        {name: "Kidney beans, dry, boiled", density: 0.79},
        {name: "Kidney beans, dry, raw", density: 0.75},
        {name: "Kidney beans, green, boiled", density: 0.7},
        {name: "Kidney beans, green, raw", density: 0.68},
        {name: "Lentils, green, small, boiled", density: 0.85},
        {name: "Lentils, green, small, raw", density: 0.89},
        {name: "Pigeon peas, boiled", density: 0.75},
        {name: "Pigeon peas, raw", density: 0.84},
        {name: "Soybean", density: 0.74},
        {name: "Soybean, flakes", density: 0.58},
        {name: "Soybean, hulls", density: 0.4},
        {name: "Soybean, meal", density: 0.64},
        {name: "Soybean, boiled", density: 0.79},
        {name: "Soybean, boiled with fat", density: 0.70},

        // Herbs and spices
        
        {name: "Basil", density: 0.085},
        {name: "Chives, raw", density: 0.203},
        {name: "Cinnamon, powder", density: 0.56},
        {name: "Clover, seed", density: 0.77},
        {name: "Fennel, seed (whole)", density: 0.392},
        {name: "Garlic, flakes", density: 0.35},
        {name: "Garlic, powder", density: 0.32},
        {name: "Ginger, ground", density: 0.352},
        {name: "Nutmeg, ground", density: 0.473},
        {name: "Oregano, dried", density: 0.203},
        {name: "Paprika", density: 0.46},
        {name: "Parsley, dried", density: 0.108},
        {name: "Pepper, black, ground", density: 0.568},
        {name: "Sage, leaves", density: 0.29},
        {name: "Spice, barbecue", density: 0.48},
        {name: "Spice, blend", density: 0.58},
        {name: "Thyme, dried, ground", density: 0.291},
        {name: "Thyme, leaves", density: 0.243},
        {name: "Thyme, leaves, dried", density: 0.183},
        {name: "Turmeric, ground", density: 0.636},
        {name: "Turmeric, powder", density: 0.406},
        {name: "Vinegar", density: 0.972},
        {name: "Vinegar, apple cider", density: 0.972},
        {name: "Vinegar, balsamic", density: 0.973},
        {name: "Vinegar, rice", density: 0.972},

        // Egg and egg products

        {name: "Egg, yoke, powder", density: 0.37},
        {name: "Egg, boiled or poached", density: 0.6},
        {name: "Eggs, powdered", density: 0.35},

        // Meat and meat products

        {name: "Blood, flour", density: 0.48},
        {name: "Blood, meal", density: 0.62},
        {name: "Bone and meat meal, loose", density: 0.72},
        {name: "Bone meal, loose", density: 0.80},
        {name: "Broth, beef", density: 1.036},
        {name: "Broth, chicken", density: 1.052},
        {name: "Cow intestine, boiled", density: 0.58},
        {name: "Cow, lean, no bone, raw", density: 0.96},
        {name: "Cow, intestine, raw", density: 0.93},
        {name: "Goat, intestine, boiled", density: 0.56},
        {name: "Goat, intestine, raw", density: 0.83},
        {name: "Pork, fatty, with bone, boiled", density: 0.63},
        {name: "Pork, fatty, with bone, raw", density: 0.97},
        {name: "Pork, medium, with bone, boiled", density: 0.7},
        {name: "Pork, medium, with bone, raw", density: 0.93},

        //Sweets	

        {name: "Chocolate chips", density: 0.676},
        {name: "Glucolin, glucose", density: 0.4},
        {name: "Jam", density: 1.333},
        {name: "Jam, sweetened", density: 1.43},
        {name: "Jelly", density: 1.245},
        {name: "Monk fruit sweetener", density: 0.812},
        {name: "Nutella", density: 1.26},
        {name: "Stevia powder", density: 0.81},
        {name: "Sucrose", density: 0.85},
        {name: "Sugar, brown", density: 0.93},
        {name: "Sugar, dextrose", density: 0.62},
        {name: "Sugar, granulated", density: 0.7},
        {name: "Sugar, powdered", density: 0.56},
        {name: "Sugar, white", density: 0.88},
        {name: "Honey", density: 1.433},

        //Syrup, blackcurrant, undiluted

        {name: "Syrup, corn", density: 1.38},
        {name: "Syrup, corn, light", density: 1.40},
        {name: "Syrup, fruit, blackberry", density: 1.34},
        {name: "Syrup, maple", density: 1.32},
        {name: "Syrup, pancake", density: 1.312},
        {name: "Vanilla extract", density: 0.879},

        //Miscellaneous foods	

        {name: "Baking powder", density: 0.9},
        {name: "Baking soda", density: 0.974},
        {name: "Gelatin", density: 0.72},
        {name: "Monosodium glutamate", density: 1.62},
        {name: "Mustard powdered", density: 0.26},
        {name: "Protein supplement", density: 0.54},
        {name: "Salad dressing", density: 1.1},
        {name: "Salt, kosher, regular", density: 0.812},
        {name: "Salt, kosher, coarse", density: 0.974},
        {name: "Salt, sodium chloride", density: 2.165},
        {name: "Salt, table", density: 1.217},
        {name: "Salt, fine table", density: 1.38},
        {name: "Salt, granulated", density: 1.28},
        {name: "Sauce, fish", density: 1.22},
        {name: "Sauce, ketchup", density: 1.15},
        {name: "Sauce, mustard, yellow", density: 1.052},
        {name: "Sauce, mustard, dijon", density: 1.014},
        {name: "Sauce, salsa", density: 1.099},
        {name: "Sauce, soy", density: 1.12},
        {name: "Sauce, Worcestershire", density: 1.162},
        {name: "Sodium bicarbonate", density: 2.2},
        {name: "Vitamin additive", density: 0.66},
        {name: "Vitamin compound", density: 0.67},
        {name: "Vitamin enrichment", density: 0.64},
        {name: "Vitamin mix", density: 0.7},
        {name: "Vitamin powder", density: 0.56},
        {name: "Yeast", density: 0.95},

    ]
    return {list};
}